### ISSUE TITLE
Why dont you use webpack?

### ISSUE THREAD

**Issue by alejandrombc** [hardyscc/aws-nestjs-starter#1426]
More than an issue is a question 😬 . The official docs says that using webpack decrease the cold start time, because the bundle that is maded. Why dont you use it on this starter project?, is there a reason not to use it? 🤔 .

Besides that, thanks for the effort 💪

**Comment by hardyscc** [comment]
@alejandrombc Im a fans of Typescript, and serverless-plugin-typescript required zero config to use it. Also it is fairly easy to warm up your lambda by using event schedule.  
So is the serverless-webpack also work great on Typescript? I am happy to switch if it create smaller bundle.
