### ISSUE TITLE
Add docker-compose.yml

### ISSUE THREAD

**Issue by tktwong** [hardyscc/aws-nestjs-starter#157]
version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

**Comment by hardyscc** [comment]
@tktwong u should able to start it by
```bash
npm run ddb:start -- --sharedDB --inMemory  
```

**Comment by tktwong** [comment]
Thanks!
