### ISSUE TITLE
Why dynamoose was selected for ORM?

### ISSUE THREAD

**Issue by blazejkustra** [hardyscc/aws-nestjs-starter#1912]
I wanted to try this template but noticed that it still uses dynamoose, which doesn't fully support Typescript and is somewhat limited in that area. Having in mind that this repo is almost fully written in TS I would propose a change to some other package such as:
- https://github.com/blazejkustra/dynamode
- https://github.com/jeremydaly/dynamodb-toolbox

**Comment by hardyscc** [comment]
@blazejkustra Sorry that this project is currently in maintenance mode and is not intended to disrupt any previous user usage. Feel free to fork it for any other DynamoDB ORM implementation.
